### PR TITLE
Ontario-centric message in swagger header

### PR DESCRIPTION
**Pull request by weiiv**

### CODE REVIEW

**Comment by ianco** [comment]
Hi @weiiv , we've started to enforce commit signing in this repository, because eventually the code is getting migrated to indy-catalyst and then eventually to a hyperledger repository, so we've started to enforce their requriements.  Can you sign your commit?  And then we can merge it.

**Comment by swcurran** [comment]
@ianco - do you have a good link to instructions on how updating a commit is done? Good to provide that. And how to make it happen by default.

**Comment by ianco** [comment]
@swcurran  I hadn't put together any instructions for this, do we have anything for the indy-catalyst repo from when we enabled this a few weeks ago?

**Comment by swcurran** [comment]
The accepted answer on this is thread should work.

https://stackoverflow.com/questions/13043357/git-sign-off-previous-commits
Not my favourite because there is a lot of other stuff on this page, but I would try that first.

**Pull request closed without merging**
