### PR TITLE
Work-around for NPE on blank expiry date

### PR DESCRIPTION
**Pull request by ianco**

### CODE REVIEW

**Comment by ianco** [comment]
@cywolf I don't know what's getting passed through, but to reproduce setup an agent with a credential with an optional date field, and then submit with an empty date.

In the von-agent-template project, like this:  https://github.com/bcgov/von-agent-template/blob/master/von-x-agent/config/schemas.yml#L34

Then on the UI:  https://github.com/bcgov/von-agent-template/blob/master/von-x-agent/config/routes.yml#L49

... then fill in the form on the UI, leave the date blank, and submit.

This is recent (yesterday) and has all updates.

**Comment by cywolf** [comment]
@ianco It looks like the form is passing in a date, not a datetime, and parse_datetime is just returning None. So I guess the question is whether it should handle plain dates (and add a time) or throw an exception.

**Comment by ianco** [comment]
It's not an issue when I actually pass a value.  The error occurs when I submit the form but leave the optional date value empty.  If I submit the credential using the REST service and leave the attribute out completely it also works fine ...

**Comment by cywolf** [comment]
Can you check what it's actually submitting from the form? I don't think it's empty.

**Comment by ianco** [comment]
Aha!  expiry_date: "NaN"

**Comment by cywolf** [comment]
Looks like somebody added moment.js handling..

https://github.com/bcgov/von-agent-template/blob/a8ba71445fc5f0292a300ee504b055ec93e0ac32/von-x-agent/assets/js/main.js#L24

I added a fix to the OrgBook to reject the invalid value.

**Comment by ianco** [comment]
@cywolf  what's the correction for the "moment handling" in main.js?  This is from the code originally provided to the bc-reg agent (and is now in all of our agents)

**Comment by ianco** [comment]
Fixed the fix of the fix

**Pull request merged**
