### PR TITLE
Configuration driven API output

### PR DESCRIPTION
**Pull request by mitovskaol**
Enabled including only specific data fields in the API responses that is based on the configuration associated with the active TOB_THEME (i.e. custom_settings_ongov.py or customn_settings_bcgov.py).
The hook is currently only implemented for Location API endpoints. By default no Location fields is returned. Custom settings for each TOB_THEME MUST include a list of Location fields that will be included in the API response and therefore displayed in the UI.

### CODE REVIEW

**Comment by WadeBarnes** [comment]
I've added the OpenShift updates to the PR.

**Comment by cywolf** [comment]
@WadeBarnes The hard-coded URL is just a default value for people running the front-end but not the API (not using docker compose).

**Comment by swcurran** [comment]
@WadeBarnes  @cywolf - who owns this and is moving it forward?  Has it fallen between the cracks?  This should not be open this long, should it?

**Comment by WadeBarnes** [comment]
It has not fallen through the cracks.  We are waiting on @mitovskaol to make the requested changes.  She has been on training and holidays.

**Comment by swcurran** [comment]
Can others make the changes, or are they significant and require Olena?  Olena is away for a couple of weeks and we don't want to be held up.

**Comment by WadeBarnes** [comment]
In that case, I’ll look into making the changes.

**Pull request merged**
